# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    -   id: autopep8
# -   repo: local
#     hooks:
#     -   id: pytest
#         name: pytest
#         entry: pytest
#         language: system
#         pass_filenames: false
#         always_run: true
#         stages: [commit]
