# Generated by Django 3.2.3 on 2021-05-31 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapist', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('level', models.SmallIntegerField(
                    null=True, verbose_name='Grado')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                 to='teacher.teacher', verbose_name='Maestro')),
                ('terapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                 to='therapist.therapist', verbose_name='Terapista')),
            ],
            options={
                'verbose_name': 'Materia',
            },
        ),
    ]
