# Generated by Django 3.2.3 on 2021-06-02 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_terapist_course_therapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(
                1), django.core.validators.MaxValueValidator(6)], verbose_name='Grado'),
        ),
    ]
