# Generated by Django 3.2.3 on 2021-06-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.SmallIntegerField(null=True, verbose_name='Grado'),
        ),
    ]
