# Generated by Django 3.2.3 on 2021-06-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('content', '0001_initial'),
        ('therapist', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('color', models.CharField(choices=[('yellow', 'Amarillo'), ('blue', 'Azul'), ('red', 'Rojo'), (
                    'black', 'Negro'), ('green', 'Verde')], max_length=10, null=True, verbose_name='Color')),
                ('description', models.TextField(
                    blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Emoción',
                'verbose_name_plural': 'Emociones',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='Modificado')),
                ('notes', models.TextField(
                    blank=True, null=True, verbose_name='Notas')),
                ('observations', models.TextField(blank=True,
                 null=True, verbose_name='Observaciones')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 to='content.content', verbose_name='Contenido')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 to='session.emotion', verbose_name='Emoción')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 to='student.student', verbose_name='Paciente')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                 to='teacher.teacher', verbose_name='Maestro')),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                 to='therapist.therapist', verbose_name='Terapista')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
            },
        ),
    ]
