# Generated by Django 3.2.3 on 2021-06-07 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='therapist',
        ),
        migrations.AlterField(
            model_name='session',
            name='emotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='session.emotion', verbose_name='Emoción'),
        ),
    ]
