# Generated by Django 3.2.3 on 2021-06-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='student.student', verbose_name='Estudiante'),
        ),
    ]
