# Generated by Django 3.2.3 on 2021-06-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='Aplica'),
            preserve_default=False,
        ),
    ]
