# Generated by Django 3.2.3 on 2021-06-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('DP', 'Disciplina Positiva'), ('DO', 'Docente'), (
                'PS', 'Psicopedagógico')], max_length=2, verbose_name='Departamento'),
        ),
    ]
