# Generated by Django 3.2.3 on 2021-06-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('level', models.CharField(choices=[
                 ('K', 'Kinder'), ('P', 'Primaria')], default='K', max_length=1, verbose_name='Nivel')),
                ('grade', models.SmallIntegerField(
                    null=True, verbose_name='Grado')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                 to='teacher.teacher', verbose_name='Maestro')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
    ]
