# Generated by Django 3.2.3 on 2021-06-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='therapist',
        ),
    ]
