# Generated by Django 3.2.3 on 2021-05-31 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dob', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[
                 ('M', 'Hombre'), ('F', 'Mujer')], default='F', max_length=1, verbose_name='Sexo')),
                ('diagnosis', models.TextField(blank=True,
                 null=True, verbose_name='Diágnostico')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                 to='course.course', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Paciente',
            },
        ),
    ]
