# Generated by Django 3.2.3 on 2021-06-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dob', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[
                 ('M', 'Hombre'), ('F', 'Mujer')], default='F', max_length=1, verbose_name='Sexo')),
                ('diagnosis', models.TextField(blank=True,
                 null=True, verbose_name='Diágnostico')),
                ('grade', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grade.grade', verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudianes',
            },
        ),
    ]
