# Generated by Django 3.2.3 on 2021-06-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='Modificado')),
                ('title', models.CharField(max_length=100,
                 unique=True, verbose_name='Título')),
                ('url', models.CharField(max_length=100, verbose_name='URL del video')),
                ('description', models.CharField(blank=True,
                 max_length=100, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
    ]
