# Generated by Django 3.2.3 on 2021-05-31 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='session.emotion', verbose_name='Emoción'),
        ),
    ]
